/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkPAtelierRouteImport } from './routes/work.p-atelier'
import { Route as MarketingPAtelierRouteImport } from './routes/marketing.p-atelier'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkPAtelierRoute = WorkPAtelierRouteImport.update({
  id: '/p-atelier',
  path: '/p-atelier',
  getParentRoute: () => WorkRoute,
} as any)
const MarketingPAtelierRoute = MarketingPAtelierRouteImport.update({
  id: '/marketing/p-atelier',
  path: '/marketing/p-atelier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRouteWithChildren
  '/marketing/p-atelier': typeof MarketingPAtelierRoute
  '/work/p-atelier': typeof WorkPAtelierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRouteWithChildren
  '/marketing/p-atelier': typeof MarketingPAtelierRoute
  '/work/p-atelier': typeof WorkPAtelierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/work': typeof WorkRouteWithChildren
  '/marketing/p-atelier': typeof MarketingPAtelierRoute
  '/work/p-atelier': typeof WorkPAtelierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/process'
    | '/services'
    | '/work'
    | '/marketing/p-atelier'
    | '/work/p-atelier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/process'
    | '/services'
    | '/work'
    | '/marketing/p-atelier'
    | '/work/p-atelier'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/process'
    | '/services'
    | '/work'
    | '/marketing/p-atelier'
    | '/work/p-atelier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  WorkRoute: typeof WorkRouteWithChildren
  MarketingPAtelierRoute: typeof MarketingPAtelierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/p-atelier': {
      id: '/work/p-atelier'
      path: '/p-atelier'
      fullPath: '/work/p-atelier'
      preLoaderRoute: typeof WorkPAtelierRouteImport
      parentRoute: typeof WorkRoute
    }
    '/marketing/p-atelier': {
      id: '/marketing/p-atelier'
      path: '/marketing/p-atelier'
      fullPath: '/marketing/p-atelier'
      preLoaderRoute: typeof MarketingPAtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkRouteChildren {
  WorkPAtelierRoute: typeof WorkPAtelierRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkPAtelierRoute: WorkPAtelierRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  WorkRoute: WorkRouteWithChildren,
  MarketingPAtelierRoute: MarketingPAtelierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
